//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 20/09/2022 10:58:29 pm
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using FrontDeskApp.Entities;

namespace FrontDeskApp.Data
{
    public partial class CustomerRepository : EntityFrameworkRepository<FrontDeskApp.Entities.Customer>, ICustomerRepository
    {
        public CustomerRepository(FrontDeskApp.Context.FrontDeskAppDbModel context)
            : base(context)
        {
        }

        public virtual ICollection<FrontDeskApp.Entities.Customer> GetAll()
        {
            return objectSet.ToList();
        }

        public virtual FrontDeskApp.Entities.Customer GetByKey(int _CustomerId)
        {
            return objectSet.SingleOrDefault(e => e.CustomerId == _CustomerId);
        }

        public new FrontDeskApp.Context.FrontDeskAppDbModel Context 
        {
            get
            {
                return (FrontDeskApp.Context.FrontDeskAppDbModel)base.Context;
            }
        }
    }
}
