//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 14/09/2022 7:16:18 am
//
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using FrontDeskApp.Entities;

namespace FrontDeskApp.Data
{
    public partial class TransactionRepository
    {
    }
}
