//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 20/09/2022 10:58:30 pm
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json;

namespace FrontDeskApp.Data.DTO
{

    public partial class AreaBoxDto
    {
        #region Constructors

        public AreaBoxDto() {
        }

        public AreaBoxDto(int areaBoxId, string name, string areaType, string status, List<TransactionDto> transactions) {

          this.AreaBoxId = areaBoxId;
          this.Name = name;
          this.AreaType = areaType;
          this.Status = status;
          this.Transactions = transactions;
        }

        #endregion

        #region Properties

        [Key]
        [Required()]
        public int AreaBoxId { get; set; }

        [StringLength(10)]
        [Required()]
        public string Name { get; set; }

        [StringLength(10)]
        public string AreaType { get; set; }

        [StringLength(10)]
        public string Status { get; set; }

        #endregion

        #region Navigation Properties

        public List<TransactionDto> Transactions { get; set; }

        #endregion
    }

}
