//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 20/09/2022 10:58:30 pm
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Newtonsoft.Json;

namespace FrontDeskApp.Data.DTO
{

    public partial class TransactionDto
    {
        #region Constructors

        public TransactionDto() {
        }

        public TransactionDto(int transactionId, int customerId, int areaBoxId, System.DateTime dateStored, System.DateTime dateRetrieved, string status, CustomerDto customer, AreaBoxDto areaBox) {

          this.TransactionId = transactionId;
          this.CustomerId = customerId;
          this.AreaBoxId = areaBoxId;
          this.DateStored = dateStored;
          this.DateRetrieved = dateRetrieved;
          this.Status = status;
          this.Customer = customer;
          this.AreaBox = areaBox;
        }

        #endregion

        #region Properties

        [Key]
        [Required()]
        public int TransactionId { get; set; }

        [Required()]
        public int CustomerId { get; set; }

        [Required()]
        public int AreaBoxId { get; set; }

        [Required()]
        public System.DateTime DateStored { get; set; }

        [Required()]
        public System.DateTime DateRetrieved { get; set; }

        [StringLength(10)]
        [Required()]
        public string Status { get; set; }

        #endregion

        #region Navigation Properties

        public CustomerDto Customer { get; set; }

        public AreaBoxDto AreaBox { get; set; }

        #endregion
    }

}
