//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// Code is generated on: 14/09/2022 7:16:18 am
//
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace FrontDeskApp.Entities
{
    public partial interface ICustomerRepository
    {
    }
}
