//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Data Transfer Object template.
// Code is generated on: 20/09/2022 10:58:30 pm
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;

namespace FrontDeskApp.Data.DTO
{

    public static partial class CustomerConverter
    {

        public static CustomerDto ToDto(this FrontDeskApp.Entities.Customer source)
        {
            return source.ToDtoWithRelated(0);
        }

        public static CustomerDto ToDtoWithRelated(this FrontDeskApp.Entities.Customer source, int level)
        {
            if (source == null)
              return null;

            var target = new CustomerDto();

            // Properties
            target.CustomerId = source.CustomerId;
            target.FirstName = source.FirstName;
            target.LastName = source.LastName;
            target.PhoneNumber = source.PhoneNumber;

            // Navigation Properties
            if (level > 0) {
              target.Transactions = source.Transactions.ToDtosWithRelated(level - 1);
            }

            // User-defined partial method
            OnDtoCreating(source, target);

            return target;
        }

        public static FrontDeskApp.Entities.Customer ToEntity(this CustomerDto source)
        {
            if (source == null)
              return null;

            var target = new FrontDeskApp.Entities.Customer();

            // Properties
            target.CustomerId = source.CustomerId;
            target.FirstName = source.FirstName;
            target.LastName = source.LastName;
            target.PhoneNumber = source.PhoneNumber;

            // User-defined partial method
            OnEntityCreating(source, target);

            return target;
        }

        public static List<CustomerDto> ToDtos(this IEnumerable<FrontDeskApp.Entities.Customer> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDto())
              .ToList();

            return target;
        }

        public static List<CustomerDto> ToDtosWithRelated(this IEnumerable<FrontDeskApp.Entities.Customer> source, int level)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToDtoWithRelated(level))
              .ToList();

            return target;
        }

        public static List<FrontDeskApp.Entities.Customer> ToEntities(this IEnumerable<CustomerDto> source)
        {
            if (source == null)
              return null;

            var target = source
              .Select(src => src.ToEntity())
              .ToList();

            return target;
        }

        static partial void OnDtoCreating(FrontDeskApp.Entities.Customer source, CustomerDto target);

        static partial void OnEntityCreating(CustomerDto source, FrontDeskApp.Entities.Customer target);

    }

}
